### ISSUE TITLE
As a user, I want to be able to create a lobby for a game

### ISSUE THREAD

**Issue by Jamin-Sulic** [sopra-fs24-16-dudo/Server#1]
**Acceptance Criteria:**
- A player can create a lobby which will have an ID
- The lobby shall be empty and public

**Priority:** major
**Estimate:** 8h 

**Development tasks:**
- [ ] sopra-fs24-16-dudo/Client#1
- [ ] sopra-fs24-16-dudo/Server#26
- [ ] sopra-fs24-16-dudo/Client#2
- [ ] sopra-fs24-16-dudo/Server#28
