### ISSUE TITLE
As a user in a game, I want to be able to see my dice at any time

### ISSUE THREAD

**Issue by Jamin-Sulic** [sopra-fs24-16-dudo/Server#10]
**Acceptance Criteria:**
- The dice are displayed at all times in the player’s screen
- The users own dices are displayed and the dices of the other players are kept hidden

**Priority:** major
**Estimate:** 8h 

**Development tasks:**
- [x] sopra-fs24-16-dudo/Client#19
- [x] sopra-fs24-16-dudo/Client#20
- [x] sopra-fs24-16-dudo/Client#21
- [x] sopra-fs24-16-dudo/Client#22
