### ISSUE TITLE
As a user, I want to throw my dice at the beginning of each round and I must not be able to change my hand

### ISSUE THREAD

**Issue by Jamin-Sulic** [sopra-fs24-16-dudo/Server#11]
**Acceptance Criteria:**
- At the beginning of each round, each player throws their 5 dice
- A player is only allowed to throw once at the beginning of each round

**Priority:** major
**Estimate:** 8h 

**Development tasks:**
- [x] sopra-fs24-16-dudo/Server#63
- [x] sopra-fs24-16-dudo/Server#64
- [x] sopra-fs24-16-dudo/Server#65
- [x] sopra-fs24-16-dudo/Client#26
