### ISSUE TITLE
As a user, I want to be able to read the instructions at any point (in the lobby or during a game), so that I am aware of how the game works

### ISSUE THREAD

**Issue by Jamin-Sulic** [sopra-fs24-16-dudo/Server#12]
**Acceptance Criteria:**
- In the lobby and in the game, there is a button that opens a pop-up that displays the rules of the game

**Priority:** minor
**Estimate:** 4h 

**Development tasks:**
- [x] sopra-fs24-16-dudo/Client#27
- [x] sopra-fs24-16-dudo/Server#68
- [x] sopra-fs24-16-dudo/Client#28
- [x] sopra-fs24-16-dudo/Client#29
