### ISSUE TITLE
As a user, I want to be able to vote out a player in the lobby, so that i can remove players that joined randomly

### ISSUE THREAD

**Issue by Jamin-Sulic** [sopra-fs24-16-dudo/Server#13]
**Acceptance Criteria:**
- At any point during a game, the players can vote to kick out a member of the game
- If all players vote to kick out a player, the player gets kicked out and the current round is restarted. 

**Priority:** critical
**Estimate:** 10h 

**Development tasks:**
- [ ] sopra-fs24-16-dudo/Server#71
- [ ] sopra-fs24-16-dudo/Server#72
- [ ] sopra-fs24-16-dudo/Server#73
- [ ] sopra-fs24-16-dudo/Server#74
- [ ] sopra-fs24-16-dudo/Client#30
