### ISSUE TITLE
As a user, I want to be able to use the voice chat during the game

### ISSUE THREAD

**Issue by Jamin-Sulic** [sopra-fs24-16-dudo/Server#14]
**Acceptance Criteria:**
- During the game a user can press on a button that will enable the voice chat
- Spectators can also use the voice chat

**Priority:** critical
**Estimate:** 12h 

**Development tasks:**
- [x] sopra-fs24-16-dudo/Server#76
- [ ] sopra-fs24-16-dudo/Client#31
- [ ] sopra-fs24-16-dudo/Server#78
- [x] sopra-fs24-16-dudo/Server#79
- [x] sopra-fs24-16-dudo/Client#32
