### ISSUE TITLE
As a user, I want to be able to make a bid on my turn

### ISSUE THREAD

**Issue by Jamin-Sulic** [sopra-fs24-16-dudo/Server#16]
**Acceptance Criteria:**
- A  user can make a bid in their turn
- The valid options shall be displayed on the screen 

**Priority:** critical
**Estimate:** 10h 

**Development tasks:**
- [x] sopra-fs24-16-dudo/Server#83
- [x] sopra-fs24-16-dudo/Client#34
- [x] sopra-fs24-16-dudo/Server#85
- [x] sopra-fs24-16-dudo/Server#86
- [x] sopra-fs24-16-dudo/Server#87
