### ISSUE TITLE
As a user, I want to be able to dudo

### ISSUE THREAD

**Issue by Jamin-Sulic** [sopra-fs24-16-dudo/Server#17]
**Acceptance Criteria:**
- Dudo ends the round
- The cards shall be counted and the loser shall be displayed
- The loser shall lose a coin
- If a player is out of the game, it shall be displayed like so

**Priority:** critical
**Estimate:** 10h 

**Development tasks:**
- [x] sopra-fs24-16-dudo/Server#88
- [x] sopra-fs24-16-dudo/Server#89
- [x] sopra-fs24-16-dudo/Server#90
- [x] sopra-fs24-16-dudo/Server#91
- [x] sopra-fs24-16-dudo/Server#92
- [x] sopra-fs24-16-dudo/Client#23
