### ISSUE TITLE
If the starting player is out of coins, a fijo round shall be played

### ISSUE THREAD

**Issue by Jamin-Sulic** [sopra-fs24-16-dudo/Server#18]
**Acceptance Criteria:**
- Aces are no jokers in this round
- Only other fijo players can change the suit

**Priority:** critical
**Estimate:** 8h 

**Development tasks:**
- [x] sopra-fs24-16-dudo/Server#94
- [x] sopra-fs24-16-dudo/Server#95
- [x] sopra-fs24-16-dudo/Server#96
- [x] sopra-fs24-16-dudo/Client#24
- [x] sopra-fs24-16-dudo/Client#25
