### ISSUE TITLE
As a user, I want to be able to join a lobby with a given ID

### ISSUE THREAD

**Issue by Jamin-Sulic** [sopra-fs24-16-dudo/Server#2]
**Acceptance Criteria:**
- If a user inputs a valid ID, they shall join the desired lobby
- A lobby can have a maximum of 6 players

**Priority:** major
**Estimate:** 8h 

**Development tasks:**
- [x] sopra-fs24-16-dudo/Client#6
- [x] sopra-fs24-16-dudo/Client#5
- [x] sopra-fs24-16-dudo/Server#31
