### ISSUE TITLE
As a logged-in user in a game lobby, I want to be able to start a game with other people by clicking on a button in the lobby page

### ISSUE THREAD

**Issue by Jamin-Sulic** [sopra-fs24-16-dudo/Server#4]
**Acceptance Criteria:**
- The “Start Game” button puts the user in a lobby with other users that pressed the button
- Upon entering the lobby a screen is displayed containing the current lobby leaderboard and the other users that are in the lobby
- The lobby can be left by pressing the “Exit Lobby” button

**Priority:** critical
**Estimate:** 8h 

**Development tasks:**
- [x] sopra-fs24-16-dudo/Client#9
- [x] sopra-fs24-16-dudo/Server#34
- [x] sopra-fs24-16-dudo/Server#35
