### ISSUE TITLE
As a user in a lobby, I want to have a “ready” button to press when I want to play, so that the game starts when all players are ready

### ISSUE THREAD

**Issue by Jamin-Sulic** [sopra-fs24-16-dudo/Server#6]
**Acceptance Criteria:**
- In the lobby, a “ready” button is displayed
- Once the button is pressed, the user’s state changes to ready
- When all users in the lobby are ready, the game automatically starts
- The game requires 2-6 players to be able to start

**Priority:** critical
**Estimate:** 10h 

**Development tasks:**
- [x] sopra-fs24-16-dudo/Client#14
- [x] sopra-fs24-16-dudo/Server#41
- [x] sopra-fs24-16-dudo/Server#42
- [x] sopra-fs24-16-dudo/Server#43
- [x] sopra-fs24-16-dudo/Server#44
- [ ] sopra-fs24-16-dudo/Server#45
