### ISSUE TITLE
As a user, I want to be able to go back to the lobby once the game is finished

### ISSUE THREAD

**Issue by Jamin-Sulic** [sopra-fs24-16-dudo/Server#8]
**Acceptance Criteria:**
- At the end of every game the winner will be displayed 
- The user can see the name of the winner and press a “Back to Lobby” button that will bring him back to the lobby.
- The leaderboard in the lobby will be updated, the winner gets 2 points if they won without losing any coins, else they get 1 point

**Priority:** critical
**Estimate:** 6h 

**Development tasks**:
- [x] sopra-fs24-16-dudo/Server#50
- [x] sopra-fs24-16-dudo/Server#51
- [x] sopra-fs24-16-dudo/Client#15
- [x] sopra-fs24-16-dudo/Server#53
- [x] sopra-fs24-16-dudo/Server#54
