### ISSUE TITLE
As a user in a game, I want to be able to see how many players are left and how many tokens each of them have

### ISSUE THREAD

**Issue by Jamin-Sulic** [sopra-fs24-16-dudo/Server#9]
**Acceptance Criteria:**
- In the game interface, the players can see the following information for each other player: Username, active or spectator status, tokens

**Priority:** critical
**Estimate:** 8h 

**Development tasks:**
- [x] sopra-fs24-16-dudo/Client#16
- [x] sopra-fs24-16-dudo/Server#56
- [x] sopra-fs24-16-dudo/Server#102
- [x] sopra-fs24-16-dudo/Client#18
